# Bidirectional Encoder Representations from Transformers (BERT)
**BERT (Bidirectional Encoder Representations from Transformers)** is a pre-trained deep learning model developed by Google for natural language processing (NLP) tasks. It uses a transformer-based architecture to learn contextual relations between words in a sentence or text. BERT is trained on a large corpus of text data and can be fine-tuned for various NLP tasks such as question answering, sentiment analysis, and text classification. BERT has achieved state-of-the-art results on several benchmark datasets in the NLP field.

Let's assume you work on a text classification task where input to the model is a word and you want to classify the words either to be person or country. 

<img src = "img.jpg" width = "800px" height = "600px"></img>

<img src = "img2.jpg" width = "800px" height = "600px"></img>

* Now think how the model process these words? Means how can we capture similarities between two words?

<img src = "img1.jpg" width = "800px" height = "600px"></img>

* So the simple answer to the question is: We look to the features of each input word and then compare them with each other if they're similary then will be classify in the same category as shown in the bellow image:
* The image shows us that the first two homes are similar but the third one is not similar with previous two homes.

<img src = "img3.jpg" width = "800px" height = "600px"></img>

* Similarly we represent the person and country names as features and finally we can decide whether it's person or country.

<img src = "img4.jpg" width = "800px" height = "600px"></img>

<img src = "img5.jpg" width = "800px" height = "600px"></img>

<img src = "img6.jpg" width = "800px" height = "600px"></img>

* So the approach covered in the upper images are representing text as number using 'Word2Vec'. The main issue of 'Word2Vec' is, it's generate fixed embedding or generate fixed vectors for similar words. It means one word using with different context might give different meaning, so this is the main issue using 'Word2Vec'.

<img src = "img7.jpg" width = "800px" height = "600px"></img>

* So based on the mentioned problem, we need to have a model to generate contextualize meaning of a word. It means based on studying the whole sentence model will generate a number representation for a specifict word. 
### So BERT allow us to do the exact same thing.

* BERT can generate contextualized embedding. At the same time it will capture the meaning of the word in a right way. As we see in the following image the words 'fair' and 'unbiased' are a kind of similar, so the model will generate almost the same vectors. Similarly the word 'fair' in sentence number 3 in the following image and the word 'Canival' has most similarity, so the model will generate almost the same vectors for these two words.

<img src = "img8.png" width = "800px" height = "600px"></img>

* **BERT** can also generate the embedding for the entire sentence. For the whole sentence it will generate a single vector.**

<img src = "img9.jpg" width = "800px" height = "600px"></img>

* BERT was trained by Google on **2500 Milions words of Wikipedia** and **800 Milions words of different books.**

<img src = "img10.jpg" width = "800px" height = "600px"></img>

* For training they use two approaches:
    1. Mased Language Model
    2. Next sentence prediction
* So today **Google Search** is powered by BERT. When you searching something, when you type the first 1 word or 2 words then they will give you suggestions for your search.

<img src = "img11.jpg" width = "800px" height = "600px"></img>

* Links for more about BERT:
    http://jalammar.github.io/a-visual-guide-to-using-bert-for-the-first-time/

* Now let's look into tensorflow code and generate some sentence and words embedding.
* So to locate BERT model we go to **tensorflow hub** which is the repository of all the different models. Go to word embedding then to BERT, here you will see a section for BERT. BERT has different models which is listed here... so we'll use the simple one which has 12 encoders. 

In [6]:
# Required libraries:
import tensorflow_hub as hub
import tensorflow_text as text

* BERT models tensorflow hub link: https://tfhub.dev/google/collections/bert/1

In [9]:
# The best thing with BERT is that, we can directly take the URL and past it in the Jupyter ('encoders') to use it. 
# Then for each model we have a pre-processing URL which can pre-process you text.

# preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
# encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"

encoder_url = "bert_en_uncased_L-12_H-768_A-12_4"
preprocess_url = "bert_en_uncased_preprocess_3"

In [10]:
# So next we create a hub layer which takes pre-process URL as an argument. It gives you like function pointer. Then we can 
# supply a buch of statements and it will do pre-process on those statements.

bert_preprocess_model = hub.KerasLayer(preprocess_url)


In [11]:
# So let's say here we build a movie classification model. So we pass couple of statements to be pre-processed by the model.
# The output of this function pointer is gonna be dictionary so we just print the key becaus the object may be big:
text_test = ['nice movie indeed','I love python programming']
text_preprocessed = bert_preprocess_model(text_test)
text_preprocessed.keys()

dict_keys(['input_mask', 'input_type_ids', 'input_word_ids'])

In [12]:
# So the two sentences are pre-processed.
# Now we can check individual elements in this dictionary. The first one is 'input_mask'. 
text_preprocessed['input_mask']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])>

* So we see the shape is (2, 128), 2 is because of: we have two sentences, and for each sentence we see the mask. So as we see the first sentence has three words but the BERT generated 5 ones (1s). The reason is the way BERT work, it add a special token called 'CLS' at the beginning and to separte two sentences it use 'SEP' token. Now if we count it it will be 5. The idea is similar for the second sentece. 128 is a kind of maximum lenght of the sentence.


In [13]:
# So the next element is 'input_type_ids' which is pretty usefull. So it assign special number to each word because this is 
# pre-proecssing step, in next step we do word embedding.

# text_preprocessed['input_type_ids']
text_preprocessed['input_word_ids']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  3835,  3185,  5262,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

### Special Tokens:
* **101 --> CLS token**
* **102 --> SEP token**

In [14]:
# Once the pre-processing steps is done, we want to create another layer and it will have the encoder URL.
# This layer we'll called BERT model. So as before it will return like function pointer and we can supply our pre-process 
# text and as result it will generate word embedding for the sentencess.
# Again we just call the keys.

bert_model = hub.KerasLayer(encoder_url)
bert_results = bert_model(text_preprocessed)
bert_results.keys()

dict_keys(['default', 'encoder_outputs', 'pooled_output', 'sequence_output'])

In [15]:
# So this will have three keys, the first one is 'pooled_output'. 
# 'Pooled_output' is the embedding for the entire sentence.
bert_results['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.7917739 , -0.214119  ,  0.49769554, ...,  0.2446523 ,
        -0.4733446 ,  0.8175868 ],
       [-0.91712296, -0.4793517 , -0.7865697 , ..., -0.6175173 ,
        -0.7102685 ,  0.92184293]], dtype=float32)>

* So we see, we had two sentences, and we see the embedding for the two sentences. The embedding vector size is 768. So this vector nicely represent the statement 'nice movie indeed' in form of numbers. Similarly we have other embedding vector for the 2nd sentence.
* So these embeddings are pretty powerful and we can use it for our NLP task, it could be movie review classification, name entity recognization, it could be anything, but BERT help you to generate a meaningful vectors out of your statement.

In [16]:
# Now let's look out to the 2nd key which is 'sequence_output'. 
# 'sequence_output' is individual word embedding vectors. 2 is again for 2 sentences, 128 means: we've 128 padding for each
# sentence and for each of the word inside the sentence we will have 768 size vector.
# The paddings (numbers) are because of contextualize embedding. 
bert_results['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07292053,  0.08567811,  0.14476846, ..., -0.09677067,
          0.08722128,  0.07711104],
        [ 0.1783935 , -0.19006078,  0.5034942 , ..., -0.05869839,
          0.32717115, -0.15578555],
        [ 0.18701448, -0.43388778, -0.48875168, ..., -0.15502736,
          0.00145129, -0.2447096 ],
        ...,
        [ 0.12083042,  0.1288426 ,  0.4645356 , ...,  0.07375526,
          0.17441978,  0.165221  ],
        [ 0.07967852, -0.01190632,  0.50225437, ...,  0.13777742,
          0.21002209,  0.00624598],
        [-0.07212704, -0.28303427,  0.5903336 , ...,  0.47551903,
          0.16668484, -0.08920316]],

       [[-0.0790059 ,  0.3633513 , -0.21101557, ..., -0.1718373 ,
          0.16299753,  0.6724265 ],
        [ 0.27883515,  0.43716335, -0.3576473 , ..., -0.04463643,
          0.38315186,  0.5887984 ],
        [ 1.2037671 ,  1.0727018 ,  0.4840877 , ...,  0.24921034,
          0.40730911,  0.4048181 ],
        ...,

In [20]:
# If you look at 'encoder_output', if we display the len of 'encoder_output', it will be 12. The reason is we're use the 
# small size BERT base. Means this BERT model has 12 encoder layers and each layer has 768 size embedding vectors.
len(bert_results['encoder_outputs'])

12

In [21]:
# The output of 'encoder_output' is nothing but the output of each individual encoder. 
bert_results['encoder_outputs'][0]

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.12901425,  0.00644747, -0.0361497 , ...,  0.04999633,
          0.06149192, -0.02657545],
        [ 1.1753384 ,  1.2140784 ,  1.1569979 , ...,  0.11634396,
         -0.35855335, -0.40490183],
        [ 0.03859042,  0.5386996 , -0.21089777, ...,  0.21858197,
          0.7260167 , -1.1158603 ],
        ...,
        [-0.07587016, -0.254219  ,  0.7075511 , ...,  0.50541997,
         -0.1887868 ,  0.15028326],
        [-0.16066615, -0.28089687,  0.5759706 , ...,  0.52758557,
         -0.11141385,  0.02887541],
        [-0.0442816 , -0.2027959 ,  0.5909355 , ...,  0.8133834 ,
         -0.39075816, -0.02601739]],

       [[ 0.1890359 ,  0.02752548, -0.0651374 , ..., -0.00620213,
          0.15053894,  0.03165445],
        [ 0.5916149 ,  0.7589137 , -0.07240661, ...,  0.6190394 ,
          0.8292891 ,  0.16161954],
        [ 1.4460827 ,  0.44602644,  0.4099025 , ...,  0.48255914,
          0.62691146,  0.13463417],
        ...,

* To get more about the elements, you can simply check the https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4 link.

* **So here next we do email classification using BERT whether email is spam or not spam?**

<img src = "img12.jpg" width = "800px" height = "600px"></img>

* So BERT will convert the email sentences (the whole email) into an embedding vectors as we saw before that the whole concept of BERT is to generate the embedding vectors for the entire sentence, so that is something that we can feed it to the neural network and do the training.
* So we'll generate an embedding vectors of 768 lenght, and then we'll supply a very simple neural network with only one dense layer (one neuron in the dense layer). As an output wi'll also put a dropout layer just to tackle the model overfitting.

<img src = "img13.jpg" width = "800px" height = "600px"></img>

* Now when you open the BERT box by the way, it has two components (pre-process and encoding) which we covered them previously. 

<img src = "img14.jpg" width = "800px" height = "600px"></img>

* Let's jump to the coding...

In [23]:
# Required libraries:
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text
import pandas as pd

In [25]:
# So the dataset which we have here is having two columns, the first one is email category and the second one is the email
# text. So let's simply read the CSV file into the notebook:
df = pd.read_csv("spam.csv")
df.head(5)

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [26]:
# So now let's do some basic analysis. 
df.groupby("Category").describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [27]:
# So we clearly see some imbalance in the dataset. 
df["Category"].value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [28]:
# So here we use 'Under-sampling' method to tackle with this problem.
# Let's check the ratio between thses two classes:
747/4825

0.15481865284974095

* So we see that 15% are spam emails and 85% are non spam emails. So the under-sampling method says that from 4825 non spam emails just pick up 747 samples and discards the others and then join it with the spam (747) emails and train the model. This is not good approach but to keep thing simple we go through this approach.


In [29]:
# So here we create a new DataFrame for 'spam' emails:
df_spam = df[df['Category']=='spam']
df_spam.shape

(747, 2)

In [34]:
# Similarly we create a new DataFrame for 'ham' emails:
df_ham = df[df['Category']=='ham']
df_ham.shape

(4825, 2)

In [35]:
# So now if we do like 'df_ham.sample(2)', then it will return 2 random samples.
df_ham.sample(2)

Category                                            Message
1385      ham  Storming msg: Wen u lift d phne, u say "HELLO"...
1506      ham  Total video converter free download type this ...

In [36]:
# So instead of 2 samples we need 747 samples.
df_ham_downsampled = df_ham.sample(df_spam.shape[0])
df_ham_downsampled.shape

(747, 2)

In [37]:
# So now we can join these two dataset for model training.
df_balanced = pd.concat([df_ham_downsampled, df_spam])
df_balanced.shape

(1494, 2)

In [38]:
# Now to check the samples from both classes:
df_balanced['Category'].value_counts()

ham     747
spam    747
Name: Category, dtype: int64

In [40]:
# Now just to priint some samples from the balanced data frame:
df_balanced.sample(5)

Category                                            Message
5073     spam  WIN a £200 Shopping spree every WEEK Starting ...
4473     spam    3. You have received your mobile content. Enjoy
907      spam  all the lastest from Stereophonics, Marley, Di...
677       ham  Maybe?! Say hi to  and find out if  got his ca...
4756      ham           U wan 2 haf lunch i'm in da canteen now.

In [41]:
# Next we create a new column for spam and ham to be represented as 1 and 0.
df_balanced['spam']=df_balanced['Category'].apply(lambda x: 1 if x=='spam' else 0)
df_balanced.sample(5)

Category                                            Message  spam
4628     spam  Please call our customer service representativ...     1
4751      ham  If you're still up, maybe leave the credit car...     0
2459      ham            Cool, I'll text you when I'm on the way     0
2361      ham  Had the money issue weigh me down but thanks t...     0
1168      ham            Lol now I'm after that hot air balloon!     0

In [42]:
# Now the DataFrame is ready and we can call train_test_split method for generating train and test samples.
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df_balanced['Message'],df_balanced['spam'], stratify=df_balanced['spam'])

In [43]:
# To see some train values:
X_train.head(4)

442                You were supposed to wake ME up &gt;:(
4226    The world suffers a lot... Not because of the ...
3244    Pls accept me for one day. Or am begging you c...
899     Thursday night? Yeah, sure thing, we'll work i...
Name: Message, dtype: object

**Now let's using BERT model get embeding vectors for few sample statements**

In [44]:
# So now as we have seen previously, we supply sentence to BERT model to generate the length vectors. So we want to create a
# simple function to take sentence as input and return the embedded vectors as output.
# So first the function takes the sentences, first we apply pre-processing and as result we get pre-precessed text and then 
# that we suppply to encoder. Then it will return a dictionary and from dictionary it will return 'pooled_output'.

def get_sentence_embeding(sentences):
    preprocessed_text = bert_preprocess(sentences)
    return bert_encoder(preprocessed_text)['pooled_output']

get_sentence_embeding([
    "500$ discount. hurry up", 
    "Bhavin, are you up for a volleybal game tomorrow?"]
)

NameError: name 'bert_preprocess' is not defined